// <auto-generated>
// This file was generated by VIServerVirtualDrawerCodeGenerator.
// DO NOT EDIT MANUALLY.
// </auto-generated>

using System;
using System.Collections.Generic;

namespace Strix.VirtualInspector.Server.Editor
{
    [VIServerVirtualObjectNameAttribute("TMPro.TMP_Style")]
    public sealed class VIServerVirtualTMProTMP_StyleDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "textStyle.m_Name",
        "textStyle.m_OpeningDefinition",
        "textStyle.m_ClosingDefinition",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("TMPro.TMP_Text")]
    public sealed class VIServerVirtualTMProTMP_TextDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "m_text",
        "m_fontAsset",
        "m_fontSize",
        "m_fontStyle",
        "m_fontWeight",
        "m_color",
        "m_enableAutoSizing",
        "m_fontSizeMin",
        "m_fontSizeMax",
        "m_lineSpacing",
        "m_paragraphSpacing",
        "m_horizontalAlignment",
        "m_verticalAlignment",
        "m_enableWordWrapping",
        "m_overflowMode",
        "m_characterSpacing",
        "m_wordSpacing",
        "m_enableKerning",
        "m_enableExtraPadding",
        "m_isRichText",
        "m_tintAllSprites",
        "m_spriteAsset",
        "m_styleSheet",
        "m_textPreprocessor",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("TMPro.TMP_TextInfo")]
    public sealed class VIServerVirtualTMProTMP_TextInfoDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
        {
        };

        public override HashSet<string> Keywords => _keywords;
    }


    [VIServerVirtualObjectNameAttribute("TMPro.TextMeshPro")]
    public sealed class VIServerVirtualTMProTextMeshProDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "m_text",
        "m_fontAsset",
        "m_fontSize",
        "m_fontStyle",
        "m_fontWeight",
        "m_color",
        "m_enableAutoSizing",
        "m_fontSizeMin",
        "m_fontSizeMax",
        "m_lineSpacing",
        "m_paragraphSpacing",
        "m_horizontalAlignment",
        "m_verticalAlignment",
        "m_enableWordWrapping",
        "m_overflowMode",
        "m_characterSpacing",
        "m_wordSpacing",
        "m_enableKerning",
        "m_enableExtraPadding",
        "m_isRichText",
        "m_tintAllSprites",
        "m_spriteAsset",
        "m_styleSheet",
        "m_textPreprocessor",
        "sortingLayerID",
        "sortingOrder",
    };

        public override HashSet<string> Keywords => _keywords;
    }


    [VIServerVirtualObjectNameAttribute("UnityEngine.AI.NavMeshAgent")]
    public sealed class VIServerVirtualUnityEngineAINavMeshAgentDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "agentTypeID",
        "baseOffset",
        "speed",
        "angularSpeed",
        "acceleration",
        "stoppingDistance",
        "autoBraking",
        "radius",
        "height",
        "obstacleAvoidanceType",
        "avoidancePriority",
        "autoTraverseOffMeshLink",
        "autoRepath",
        "areaMask",
        "isStopped",
        "updatePosition",
        "updateRotation",
        "updateUpAxis",
        "destination",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AI.NavMeshObstacle")]
    public sealed class VIServerVirtualUnityEngineAINavMeshObstacleDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "shape",
        "center",
        "size",
        "radius",
        "height",
        "carving",
        "carveOnlyStationary",
        "carvingMoveThreshold",
        "carvingTimeToStationary",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AI.OffMeshLink")]
    public sealed class VIServerVirtualUnityEngineAIOffMeshLinkDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "startTransform",
        "endTransform",
        "costOverride",
        "biDirectional",
        "activated",
        "autoUpdatePositions",
        "area",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AnchoredJoint2D")]
    public sealed class VIServerVirtualUnityEngineAnchoredJoint2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "anchor",
        "connectedAnchor",
        "autoConfigureConnectedAnchor",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Animation")]
    public sealed class VIServerVirtualUnityEngineAnimationDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "clip",
        "playAutomatically",
        "animatePhysics",
        "cullingType",
        "wrapMode",
    };

        public override HashSet<string> Keywords => _keywords;
    }


    [VIServerVirtualObjectNameAttribute("UnityEngine.Animations.AimConstraint")]
    public sealed class VIServerVirtualUnityEngineAnimationsAimConstraintDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "weight",
        "constraintActive",
        "locked",
        "rotationAtRest",
        "rotationAxis",
        "rotationOffset",
        "aimVector",
        "upVector",
        "worldUpType",
        "worldUpVector",
        "worldUpObject",
    };

        public override HashSet<string> Keywords => _keywords;
    }


    [VIServerVirtualObjectNameAttribute("UnityEngine.Animations.LookAtConstraint")]
    public sealed class VIServerVirtualUnityEngineAnimationsLookAtConstraintDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "weight",
        "constraintActive",
        "locked",
        "roll",
        "rotationAtRest",
        "rotationOffset",
        "useUpObject",
        "worldUpObject",
    };

        public override HashSet<string> Keywords => _keywords;
    }


    [VIServerVirtualObjectNameAttribute("UnityEngine.Animations.ParentConstraint")]
    public sealed class VIServerVirtualUnityEngineAnimationsParentConstraintDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "weight",
        "constraintActive",
        "locked",
        "translationAtRest",
        "translationAxis",
        "translationOffsets",
        "rotationAtRest",
        "rotationAxis",
        "rotationOffsets",
    };

        public override HashSet<string> Keywords => _keywords;
    }


    [VIServerVirtualObjectNameAttribute("UnityEngine.Animations.PositionConstraint")]
    public sealed class VIServerVirtualUnityEngineAnimationsPositionConstraintDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "weight",
        "constraintActive",
        "locked",
        "translationAtRest",
        "translationAxis",
        "translationOffset",
    };

        public override HashSet<string> Keywords => _keywords;
    }


    [VIServerVirtualObjectNameAttribute("UnityEngine.Animations.RotationConstraint")]
    public sealed class VIServerVirtualUnityEngineAnimationsRotationConstraintDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "weight",
        "constraintActive",
        "locked",
        "rotationAtRest",
        "rotationAxis",
        "rotationOffset",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Animations.ScaleConstraint")]
    public sealed class VIServerVirtualUnityEngineAnimationsScaleConstraintDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "weight",
        "constraintActive",
        "locked",
        "scaleAtRest",
        "scaleOffset",
        "scalingAxis",
    };

        public override HashSet<string> Keywords => _keywords;
    }


    [VIServerVirtualObjectNameAttribute("UnityEngine.Animator")]
    public sealed class VIServerVirtualUnityEngineAnimatorDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "avatar",
        "applyRootMotion",
        "updateMode",
        "cullingMode",
        "keepAnimatorStateOnDisable",
        "layersAffectMassCenter",
        "stabilizeFeet",
        "logWarnings",
        "speed",
        "runtimeAnimatorController",
        "avatarRoot",
        "hasRootMotion",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AreaEffector2D")]
    public sealed class VIServerVirtualUnityEngineAreaEffector2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "forceAngle",
        "useGlobalAngle",
        "forceMagnitude",
        "forceVariation",
        "forceTarget",
        "drag",
        "angularDrag",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.ArticulationBody")]
    public sealed class VIServerVirtualUnityEngineArticulationBodyDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "immovable",
        "useGravity",
        "mass",
        "linearDamping",
        "angularDamping",
        "maxAngularVelocity",
        "maxLinearVelocity",
        "solverIterations",
        "solverVelocityIterations",
        "sleepThreshold",
        "collisionDetectionMode",
        "anchorPosition",
        "anchorRotation",
        "parentAnchorPosition",
        "parentAnchorRotation",
        "matchAnchors",
        "linearLockX",
        "linearLockY",
        "linearLockZ",
        "swingYLock",
        "swingZLock",
        "twistLock",
        "xDrive",
        "yDrive",
        "zDrive",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AudioChorusFilter")]
    public sealed class VIServerVirtualUnityEngineAudioChorusFilterDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "dryMix",
        "wetMix1",
        "wetMix2",
        "wetMix3",
        "delay",
        "rate",
        "depth",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AudioDistortionFilter")]
    public sealed class VIServerVirtualUnityEngineAudioDistortionFilterDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "distortionLevel",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AudioEchoFilter")]
    public sealed class VIServerVirtualUnityEngineAudioEchoFilterDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "delay",
        "decayRatio",
        "dryMix",
        "wetMix",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AudioHighPassFilter")]
    public sealed class VIServerVirtualUnityEngineAudioHighPassFilterDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "cutoffFrequency",
        "highpassResonanceQ",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AudioListener")]
    public sealed class VIServerVirtualUnityEngineAudioListenerDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "velocityUpdateMode",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AudioLowPassFilter")]
    public sealed class VIServerVirtualUnityEngineAudioLowPassFilterDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "cutoffFrequency",
        "lowpassResonanceQ",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AudioReverbFilter")]
    public sealed class VIServerVirtualUnityEngineAudioReverbFilterDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "reverbPreset",
        "dryLevel",
        "room",
        "roomHF",
        "roomLF",
        "decayTime",
        "decayHFRatio",
        "reflectionsLevel",
        "reflectionsDelay",
        "reverbLevel",
        "reverbDelay",
        "diffusion",
        "density",
        "hfReference",
        "lfReference",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AudioReverbZone")]
    public sealed class VIServerVirtualUnityEngineAudioReverbZoneDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "reverbPreset",
        "minDistance",
        "maxDistance",
        "room",
        "roomHF",
        "roomLF",
        "decayTime",
        "decayHFRatio",
        "reflections",
        "reflectionsDelay",
        "reverb",
        "reverbDelay",
        "diffusion",
        "density",
        "HFReference",
        "LFReference",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.AudioSource")]
    public sealed class VIServerVirtualUnityEngineAudioSourceDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "clip",
        "outputAudioMixerGroup",
        "mute",
        "bypassEffects",
        "bypassListenerEffects",
        "bypassReverbZones",
        "playOnAwake",
        "loop",
        "priority",
        "volume",
        "pitch",
        "stereoPan",
        "spatialBlend",
        "reverbZoneMix",
        "dopplerLevel",
        "spread",
        "rolloffMode",
        "minDistance",
        "maxDistance",
        "spatialize",
        "spatializePostEffects",
        "velocityUpdateMode",
        "ignoreListenerPause",
        "ignoreListenerVolume",
    };

        public override HashSet<string> Keywords => _keywords;
    }


    [VIServerVirtualObjectNameAttribute("UnityEngine.Behaviour")]
    public sealed class VIServerVirtualUnityEngineBehaviourDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "enabled",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.BillboardRenderer")]
    public sealed class VIServerVirtualUnityEngineBillboardRendererDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "billboard",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.BoxCollider")]
    public sealed class VIServerVirtualUnityEngineBoxColliderDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "isTrigger",
        "sharedMaterial",
        "center",
        "size",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.BoxCollider2D")]
    public sealed class VIServerVirtualUnityEngineBoxCollider2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "isTrigger",
        "usedByEffector",
        "sharedMaterial",
        "density",
        "offset",
        "size",
        "edgeRadius",
        "autoTiling",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.BuoyancyEffector2D")]
    public sealed class VIServerVirtualUnityEngineBuoyancyEffector2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "density",
        "surfaceLevel",
        "flowAngle",
        "flowMagnitude",
        "flowVariation",
        "linearDrag",
        "angularDrag",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Camera")]
    public sealed class VIServerVirtualUnityEngineCameraDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "clearFlags",
        "backgroundColor",
        "cullingMask",
        "orthographic",
        "fieldOfView",
        "orthographicSize",
        "nearClipPlane",
        "farClipPlane",
        "rect",
        "depth",
        "renderingPath",
        "allowHDR",
        "allowMSAA",
        "allowDynamicResolution",
        "targetTexture",
        "targetDisplay",
        "useOcclusionCulling",
        "usePhysicalProperties",
        "focalLength",
        "sensorSize",
        "lensShift",
        "gateFit",
        "aperture",
        "shutterSpeed",
        "iso",
        "transparencySortMode",
        "transparencySortAxis",
        "stereoTargetEye",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Canvas")]
    public sealed class VIServerVirtualUnityEngineCanvasDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "renderMode",
        "pixelPerfect",
        "worldCamera",
        "planeDistance",
        "sortingLayerID",
        "sortingLayerName",
        "sortingOrder",
        "targetDisplay",
        "scaleFactor",
        "referencePixelsPerUnit",
        "overrideSorting",
        "additionalShaderChannels",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.CanvasGroup")]
    public sealed class VIServerVirtualUnityEngineCanvasGroupDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "alpha",
        "interactable",
        "blocksRaycasts",
        "ignoreParentGroups",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.CanvasRenderer")]
    public sealed class VIServerVirtualUnityEngineCanvasRendererDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "cull",
        "cullTransparentMesh",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.CapsuleCollider")]
    public sealed class VIServerVirtualUnityEngineCapsuleColliderDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "isTrigger",
        "sharedMaterial",
        "center",
        "radius",
        "height",
        "direction",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.CapsuleCollider2D")]
    public sealed class VIServerVirtualUnityEngineCapsuleCollider2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "isTrigger",
        "usedByEffector",
        "sharedMaterial",
        "density",
        "offset",
        "size",
        "direction",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.CharacterController")]
    public sealed class VIServerVirtualUnityEngineCharacterControllerDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "slopeLimit",
        "stepOffset",
        "skinWidth",
        "minMoveDistance",
        "center",
        "radius",
        "height",
        "detectCollisions",
        "enableOverlapRecovery",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.CharacterJoint")]
    public sealed class VIServerVirtualUnityEngineCharacterJointDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "connectedBody",
        "anchor",
        "axis",
        "swingAxis",
        "lowTwistLimit",
        "highTwistLimit",
        "swing1Limit",
        "swing2Limit",
        "twistLimitSpring",
        "swingLimitSpring",
        "enableProjection",
        "projectionDistance",
        "projectionAngle",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.CircleCollider2D")]
    public sealed class VIServerVirtualUnityEngineCircleCollider2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "isTrigger",
        "usedByEffector",
        "sharedMaterial",
        "density",
        "offset",
        "radius",
    };

        public override HashSet<string> Keywords => _keywords;
    }


    [VIServerVirtualObjectNameAttribute("UnityEngine.Cloth")]
    public sealed class VIServerVirtualUnityEngineClothDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "useGravity",
        "useTethers",
        "useVirtualParticles",
        "bendingStiffness",
        "stretchingStiffness",
        "damping",
        "friction",
        "collisionMassScale",
        "selfCollisionDistance",
        "selfCollisionStiffness",
        "clothSolverFrequency",
        "stiffnessFrequency",
        "worldVelocityScale",
        "worldAccelerationScale",
        "sleepThreshold",
        "capsuleColliders",
        "sphereColliders",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Collider")]
    public sealed class VIServerVirtualUnityEngineColliderDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "isTrigger",
        "providesContacts",
        "material",
        "sharedMaterial",
        "layerOverridePriority",
        "excludeLayers",
        "includeLayers",
        "enabled",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Collider2D")]
    public sealed class VIServerVirtualUnityEngineCollider2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "isTrigger",
        "usedByEffector",
        "usedByComposite",
        "density",
        "offset",
        "sharedMaterial",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Component")]
    public sealed class VIServerVirtualUnityEngineComponentDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
        {

        };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.CompositeCollider2D")]
    public sealed class VIServerVirtualUnityEngineCompositeCollider2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "geometryType",
        "generationType",
        "vertexDistance",
        "offsetDistance",
        "edgeRadius",
        "useDelaunayMesh",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.ConfigurableJoint")]
    public sealed class VIServerVirtualUnityEngineConfigurableJointDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "connectedBody",
        "anchor",
        "axis",
        "secondaryAxis",
        "xMotion",
        "yMotion",
        "zMotion",
        "angularXMotion",
        "angularYMotion",
        "angularZMotion",
        "linearLimitSpring",
        "linearLimit",
        "lowAngularXLimit",
        "highAngularXLimit",
        "angularYLimit",
        "angularZLimit",
        "angularXLimitSpring",
        "angularYZLimitSpring",
        "targetPosition",
        "targetVelocity",
        "xDrive",
        "yDrive",
        "zDrive",
        "targetRotation",
        "targetAngularVelocity",
        "rotationDriveMode",
        "slerpDrive",
        "projectionMode",
        "projectionDistance",
        "projectionAngle",
        "configuredInWorldSpace",
        "swapBodies",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.ConstantForce")]
    public sealed class VIServerVirtualUnityEngineConstantForceDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "force",
        "relativeForce",
        "torque",
        "relativeTorque",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.ConstantForce2D")]
    public sealed class VIServerVirtualUnityEngineConstantForce2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "force",
        "relativeForce",
        "torque",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.CustomCollider2D")]
    public sealed class VIServerVirtualUnityEngineCustomCollider2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
        {
        };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.DistanceJoint2D")]
    public sealed class VIServerVirtualUnityEngineDistanceJoint2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "autoConfigureDistance",
        "distance",
        "maxDistanceOnly",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.EdgeCollider2D")]
    public sealed class VIServerVirtualUnityEngineEdgeCollider2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "edgeRadius",
        "points",
        "useAdjacentStartPoint",
        "useAdjacentEndPoint",
        "adjacentStartPoint",
        "adjacentEndPoint",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Effector2D")]
    public sealed class VIServerVirtualUnityEngineEffector2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "useColliderMask",
        "colliderMask",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.EventSystems.BaseInputModule")]
    public sealed class VIServerVirtualUnityEngineEventSystemsBaseInputModuleDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "inputOverride",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.EventSystems.BaseRaycaster")]
    public sealed class VIServerVirtualUnityEngineEventSystemsBaseRaycasterDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "eventCamera",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.EventSystems.EventSystem")]
    public sealed class VIServerVirtualUnityEngineEventSystemsEventSystemDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "firstSelectedGameObject",
        "sendNavigationEvents",
        "pixelDragThreshold",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.EventSystems.EventTrigger")]
    public sealed class VIServerVirtualUnityEngineEventSystemsEventTriggerDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "triggers",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.EventSystems.PhysicsRaycaster")]
    public sealed class VIServerVirtualUnityEngineEventSystemsPhysicsRaycasterDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "eventMask",
        "maxRayIntersections",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.EventSystems.StandaloneInputModule")]
    public sealed class VIServerVirtualUnityEngineEventSystemsStandaloneInputModuleDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "horizontalAxis",
        "verticalAxis",
        "submitButton",
        "cancelButton",
        "inputActionsPerSecond",
        "repeatDelay",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.EventSystems.TouchInputModule")]
    public sealed class VIServerVirtualUnityEngineEventSystemsTouchInputModuleDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "forceModuleActive",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.FixedJoint2D")]
    public sealed class VIServerVirtualUnityEngineFixedJoint2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "dampingRatio",
        "frequency",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.FrictionJoint2D")]
    public sealed class VIServerVirtualUnityEngineFrictionJoint2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "maxForce",
        "maxTorque",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Grid")]
    public sealed class VIServerVirtualUnityEngineGridDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "cellLayout",
        "cellSize",
        "cellGap",
        "cellSwizzle",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.GridLayout")]
    public sealed class VIServerVirtualUnityEngineGridLayoutDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "cellLayout",
        "cellSize",
        "cellGap",
        "cellSwizzle",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.HingeJoint")]
    public sealed class VIServerVirtualUnityEngineHingeJointDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "useLimits",
        "limits",
        "useMotor",
        "motor",
        "useSpring",
        "spring",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.HingeJoint2D")]
    public sealed class VIServerVirtualUnityEngineHingeJoint2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "useLimits",
        "limits",
        "useMotor",
        "motor",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Joint")]
    public sealed class VIServerVirtualUnityEngineJointDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "connectedBody",
        "anchor",
        "axis",
        "autoConfigureConnectedAnchor",
        "connectedAnchor",
        "breakForce",
        "breakTorque",
        "enableCollision",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Joint2D")]
    public sealed class VIServerVirtualUnityEngineJoint2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "connectedBody",
        "breakForce",
        "breakTorque",
        "enableCollision",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.LODGroup")]
    public sealed class VIServerVirtualUnityEngineLODGroupDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "size",
        "fadeMode",
        "animateCrossFading",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.LensFlare")]
    public sealed class VIServerVirtualUnityEngineLensFlareDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "flare",
        "color",
        "brightness",
        "fadeSpeed",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Light")]
    public sealed class VIServerVirtualUnityEngineLightDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "type",
        "color",
        "intensity",
        "range",
        "bounceIntensity",
        "shadows",
        "shadowStrength",
        "shadowBias",
        "shadowNormalBias",
        "shadowNearPlane",
        "cookie",
        "cookieSize",
        "flare",
        "renderMode",
        "cullingMask",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.LightProbeGroup")]
    public sealed class VIServerVirtualUnityEngineLightProbeGroupDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "dering",
        "probePositions",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.LineRenderer")]
    public sealed class VIServerVirtualUnityEngineLineRendererDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "useWorldSpace",
        "loop",
        "positionCount",
        "startWidth",
        "endWidth",
        "widthMultiplier",
        "widthCurve",
        "startColor",
        "endColor",
        "colorGradient",
        "textureMode",
        "alignment",
        "generateLightingData",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.MeshCollider")]
    public sealed class VIServerVirtualUnityEngineMeshColliderDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "sharedMesh",
        "convex",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.MeshFilter")]
    public sealed class VIServerVirtualUnityEngineMeshFilterDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "sharedMesh",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.MeshRenderer")]
    public sealed class VIServerVirtualUnityEngineMeshRendererDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "materials",
        "receiveShadows",
        "shadowCastingMode",
        "lightProbeUsage",
        "reflectionProbeUsage",
        "sortingLayerID",
        "sortingOrder",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.MonoBehaviour")]
    public sealed class VIServerVirtualUnityEngineMonoBehaviourDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
        {

        };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Object")]
    public sealed class VIServerVirtualUnityEngineObjectDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
        {

        };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.OcclusionArea")]
    public sealed class VIServerVirtualUnityEngineOcclusionAreaDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "center",
        "size",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.OcclusionPortal")]
    public sealed class VIServerVirtualUnityEngineOcclusionPortalDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "open",
    };

        public override HashSet<string> Keywords => _keywords;
    }


    [VIServerVirtualObjectNameAttribute("UnityEngine.ParticleSystem")]
    public sealed class VIServerVirtualUnityEngineParticleSystemDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "main",
        "emission",
        "shape",
        "velocityOverLifetime",
        "limitVelocityOverLifetime",
        "inheritVelocity",
        "forceOverLifetime",
        "colorOverLifetime",
        "colorBySpeed",
        "sizeOverLifetime",
        "sizeBySpeed",
        "rotationOverLifetime",
        "rotationBySpeed",
        "externalForces",
        "noise",
        "collision",
        "trigger",
        "subEmitters",
        "textureSheetAnimation",
        "lights",
        "trails",
        "customData",
        "useAutoRandomSeed",
        "randomSeed",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.ParticleSystemForceField")]
    public sealed class VIServerVirtualUnityEngineParticleSystemForceFieldDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "shape",
        "startRange",
        "endRange",
        "length",
        "gravity",
        "gravityFocus",
        "rotationAttraction",
        "rotationSpeed",
        "rotationRandomness",
        "vectorField",
        "vectorFieldAttraction",
        "vectorFieldSpeed",
        "drag",
        "multiplyDragByParticleSize",
        "multiplyDragByParticleVelocity",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.PlatformEffector2D")]
    public sealed class VIServerVirtualUnityEnginePlatformEffector2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "useOneWay",
        "useOneWayGrouping",
        "useSideFriction",
        "useSideBounce",
        "surfaceArc",
        "sideArc",
        "rotationalOffset",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Playables.PlayableDirector")]
    public sealed class VIServerVirtualUnityEnginePlayablesPlayableDirectorDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "playableAsset",
        "initialTime",
        "playOnAwake",
        "timeUpdateMode",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.PointEffector2D")]
    public sealed class VIServerVirtualUnityEnginePointEffector2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "forceMagnitude",
        "forceVariation",
        "distanceScale",
        "drag",
        "angularDrag",
        "forceSource",
        "forceTarget",
        "forceMode",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.PolygonCollider2D")]
    public sealed class VIServerVirtualUnityEnginePolygonCollider2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "autoTiling",
        "pathCount",
        "points",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Projector")]
    public sealed class VIServerVirtualUnityEngineProjectorDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "nearClipPlane",
        "farClipPlane",
        "fieldOfView",
        "aspectRatio",
        "orthographic",
        "orthographicSize",
        "material",
        "ignoreLayers",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.RectTransform")]
    public sealed class VIServerVirtualUnityEngineRectTransformDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "anchorMin",
        "anchorMax",
        "anchoredPosition",
        "anchoredPosition3D",
        "sizeDelta",
        "pivot",
        "offsetMin",
        "offsetMax",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.ReflectionProbe")]
    public sealed class VIServerVirtualUnityEngineReflectionProbeDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "mode",
        "refreshMode",
        "timeSlicingMode",
        "resolution",
        "intensity",
        "size",
        "center",
        "nearClipPlane",
        "farClipPlane",
        "boxProjection",
        "clearFlags",
        "backgroundColor",
        "cullingMask",
        "useHDR",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.RelativeJoint2D")]
    public sealed class VIServerVirtualUnityEngineRelativeJoint2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "autoConfigureOffset",
        "linearOffset",
        "angularOffset",
        "correctionScale",
        "maxForce",
        "maxTorque",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Renderer")]
    public sealed class VIServerVirtualUnityEngineRendererDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "enabled",
        "material",
        "materials",
        "sharedMaterial",
        "sharedMaterials",
        "shadowCastingMode",
        "receiveShadows",
        "reflectionProbeUsage",
        "lightProbeUsage",
        "probeAnchor",
        "sortingLayerID",
        "sortingOrder",
        "rendererPriority",
        "allowOcclusionWhenDynamic",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Rigidbody")]
    public sealed class VIServerVirtualUnityEngineRigidbodyDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "mass",
        "drag",
        "angularDrag",
        "useGravity",
        "isKinematic",
        "interpolation",
        "collisionDetectionMode",
        "constraints",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Rigidbody2D")]
    public sealed class VIServerVirtualUnityEngineRigidbody2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "bodyType",
        "simulated",
        "useAutoMass",
        "mass",
        "linearDrag",
        "angularDrag",
        "gravityScale",
        "useFullKinematicContacts",
        "interpolation",
        "sleepMode",
        "collisionDetectionMode",
        "constraints",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.SkinnedMeshRenderer")]
    public sealed class VIServerVirtualUnityEngineSkinnedMeshRendererDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "sharedMesh",
        "updateWhenOffscreen",
        "rootBone",
        "bones",
        "quality",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Skybox")]
    public sealed class VIServerVirtualUnityEngineSkyboxDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "material",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.SphereCollider")]
    public sealed class VIServerVirtualUnityEngineSphereColliderDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "center",
        "radius",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.SpringJoint")]
    public sealed class VIServerVirtualUnityEngineSpringJointDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "spring",
        "damper",
        "minDistance",
        "maxDistance",
        "tolerance",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Terrain")]
    public sealed class VIServerVirtualUnityEngineTerrainDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "terrainData",
        "materialTemplate",
        "drawInstanced",
        "pixelError",
        "basemapDistance",
        "castShadows",
        "reflectionProbeUsage",
        "detailObjectDistance",
        "detailObjectDensity",
        "treeDistance",
        "treeBillboardDistance",
        "treeCrossFadeLength",
        "treeMaximumFullLODCount",
        "preserveTreePrototypeLayers",
        "allowAutoConnect",
        "groupingID",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.TerrainCollider")]
    public sealed class VIServerVirtualUnityEngineTerrainColliderDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "terrainData",
    };

        public override HashSet<string> Keywords => _keywords;
    }


    [VIServerVirtualObjectNameAttribute("UnityEngine.TextMesh")]
    public sealed class VIServerVirtualUnityEngineTextMeshDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "text",
        "font",
        "fontSize",
        "fontStyle",
        "color",
        "anchor",
        "alignment",
        "characterSize",
        "lineSpacing",
        "tabSize",
        "richText",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Tilemaps.TilemapCollider2D")]
    public sealed class VIServerVirtualUnityEngineTilemapsTilemapCollider2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "extrusionFactor",
        "useDelaunayMesh",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.TrailRenderer")]
    public sealed class VIServerVirtualUnityEngineTrailRendererDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "time",
        "minVertexDistance",
        "widthMultiplier",
        "widthCurve",
        "colorGradient",
        "startColor",
        "endColor",
        "startWidth",
        "endWidth",
        "numCapVertices",
        "numCornerVertices",
        "alignment",
        "textureMode",
        "generateLightingData",
        "shadowBias",
        "maskInteraction",
        "autodestruct",
        "emitting",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Transform")]
    public sealed class VIServerVirtualUnityEngineTransformDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "position",
        "rotation",
        "scale",
        "localPosition",
        "localRotation",
        "localScale",
        "parent",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.U2D.Animation.SpriteCategoryEntry")]
    public sealed class VIServerVirtualUnityEngineU2DAnimationSpriteCategoryEntryDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>();

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.U2D.Animation.SpriteLibCategory")]
    public sealed class VIServerVirtualUnityEngineU2DAnimationSpriteLibCategoryDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>();

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.U2D.Animation.SpriteLibrary")]
    public sealed class VIServerVirtualUnityEngineU2DAnimationSpriteLibraryDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "spriteLibraryAsset",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.U2D.Animation.SpriteResolver")]
    public sealed class VIServerVirtualUnityEngineU2DAnimationSpriteResolverDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "spriteLibrary",
        "spriteRenderer",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.U2D.Animation.SpriteSkin")]
    public sealed class VIServerVirtualUnityEngineU2DAnimationSpriteSkinDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "alwaysUpdate",
        "autoRebind",
        "rootBone",
        "spriteRenderer",
        "sprite",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.U2D.PixelPerfectCamera")]
    public sealed class VIServerVirtualUnityEngineU2DPixelPerfectCameraDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "assetsPPU",
        "refResolutionX",
        "refResolutionY",
        "upscaleRT",
        "pixelSnapping",
        "cropFrameX",
        "cropFrameY",
        "stretchFill",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.U2D.SpriteShapeRenderer")]
    public sealed class VIServerVirtualUnityEngineU2DSpriteShapeRendererDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "color",
        "maskInteraction",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.AnimationTriggers")]
    public sealed class VIServerVirtualUnityEngineUIAnimationTriggersDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "normalTrigger",
        "highlightedTrigger",
        "pressedTrigger",
        "selectedTrigger",
        "disabledTrigger",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.AspectRatioFitter")]
    public sealed class VIServerVirtualUnityEngineUIAspectRatioFitterDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "aspectMode",
        "aspectRatio",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.Button")]
    public sealed class VIServerVirtualUnityEngineUIButtonDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "onClick",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.CanvasScaler")]
    public sealed class VIServerVirtualUnityEngineUICanvasScalerDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "uiScaleMode",
        "referenceResolution",
        "screenMatchMode",
        "matchWidthOrHeight",
        "referencePixelsPerUnit",
        "scaleFactor",
        "physicalUnit",
        "fallbackScreenDPI",
        "defaultSpriteDPI",
        "dynamicPixelsPerUnit",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.ContentSizeFitter")]
    public sealed class VIServerVirtualUnityEngineUIContentSizeFitterDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "horizontalFit",
        "verticalFit",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.Dropdown")]
    public sealed class VIServerVirtualUnityEngineUIDropdownDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "template",
        "captionText",
        "captionImage",
        "itemText",
        "itemImage",
        "options",
        "onValueChanged",
        "value",
        "alphaFadeSpeed",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.Dropdown+OptionData")]
    public sealed class VIServerVirtualUnityEngineUIDropdownOptionDataDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>();

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.Dropdown+OptionDataList")]
    public sealed class VIServerVirtualUnityEngineUIDropdownOptionDataListDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>();

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.FontData")]
    public sealed class VIServerVirtualUnityEngineUIFontDataDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "font",
        "fontSize",
        "fontStyle",
        "bestFit",
        "minSize",
        "maxSize",
        "alignment",
        "alignByGeometry",
        "horizontalOverflow",
        "verticalOverflow",
        "lineSpacing",
        "richText",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.Graphic")]
    public sealed class VIServerVirtualUnityEngineUIGraphicDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "color",
        "material",
        "raycastTarget",
        "raycastPadding",
        "useLegacyMeshGeneration",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.GraphicRaycaster")]
    public sealed class VIServerVirtualUnityEngineUIGraphicRaycasterDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "ignoreReversedGraphics",
        "blockingObjects",
        "blockingMask",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.GridLayoutGroup")]
    public sealed class VIServerVirtualUnityEngineUIGridLayoutGroupDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "startCorner",
        "startAxis",
        "cellSize",
        "spacing",
        "constraint",
        "constraintCount",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.HorizontalOrVerticalLayoutGroup")]
    public sealed class VIServerVirtualUnityEngineUIHorizontalOrVerticalLayoutGroupDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "spacing",
        "childForceExpandWidth",
        "childForceExpandHeight",
        "childControlWidth",
        "childControlHeight",
        "childScaleWidth",
        "childScaleHeight",
        "reverseArrangement",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.Image")]
    public sealed class VIServerVirtualUnityEngineUIImageDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "sprite",
        "overrideSprite",
        "type",
        "preserveAspect",
        "fillCenter",
        "fillMethod",
        "fillAmount",
        "fillClockwise",
        "fillOrigin",
        "useSpriteMesh",
        "pixelsPerUnitMultiplier",
        "alphaHitTestMinimumThreshold",
        "material",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.InputField")]
    public sealed class VIServerVirtualUnityEngineUIInputFieldDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "textComponent",
        "text",
        "contentType",
        "lineType",
        "inputType",
        "characterValidation",
        "characterLimit",
        "caretBlinkRate",
        "caretWidth",
        "caretColor",
        "customCaretColor",
        "selectionColor",
        "readOnly",
        "shouldHideMobileInput",
        "onValueChanged",
        "onEndEdit",
        "placeholder",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.LayoutElement")]
    public sealed class VIServerVirtualUnityEngineUILayoutElementDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "ignoreLayout",
        "minWidth",
        "minHeight",
        "preferredWidth",
        "preferredHeight",
        "flexibleWidth",
        "flexibleHeight",
        "layoutPriority",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.LayoutGroup")]
    public sealed class VIServerVirtualUnityEngineUILayoutGroupDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "padding",
        "childAlignment",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.Mask")]
    public sealed class VIServerVirtualUnityEngineUIMaskDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "showMaskGraphic",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.MaskableGraphic")]
    public sealed class VIServerVirtualUnityEngineUIMaskableGraphicDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "maskable",
        "isMaskingGraphic",
        "onCullStateChanged",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.RawImage")]
    public sealed class VIServerVirtualUnityEngineUIRawImageDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "texture",
        "uvRect",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.RectMask2D")]
    public sealed class VIServerVirtualUnityEngineUIRectMask2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "padding",
        "softness",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.ScrollRect")]
    public sealed class VIServerVirtualUnityEngineUIScrollRectDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "content",
        "horizontal",
        "vertical",
        "movementType",
        "elasticity",
        "inertia",
        "decelerationRate",
        "scrollSensitivity",
        "viewport",
        "horizontalScrollbar",
        "verticalScrollbar",
        "onValueChanged",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.Scrollbar")]
    public sealed class VIServerVirtualUnityEngineUIScrollbarDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "direction",
        "handleRect",
        "size",
        "numberOfSteps",
        "onValueChanged",
        "value",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.Selectable")]
    public sealed class VIServerVirtualUnityEngineUISelectableDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "interactable",
        "transition",
        "colors",
        "spriteState",
        "animationTriggers",
        "navigation",
        "targetGraphic",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.Slider")]
    public sealed class VIServerVirtualUnityEngineUISliderDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "direction",
        "minValue",
        "maxValue",
        "wholeNumbers",
        "value",
        "onValueChanged",
        "fillRect",
        "handleRect",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.Text")]
    public sealed class VIServerVirtualUnityEngineUITextDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "text",
        "font",
        "fontSize",
        "fontStyle",
        "alignment",
        "alignByGeometry",
        "horizontalOverflow",
        "verticalOverflow",
        "resizeTextForBestFit",
        "resizeTextMinSize",
        "resizeTextMaxSize",
        "lineSpacing",
        "supportRichText",
        "color",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.UI.Toggle")]
    public sealed class VIServerVirtualUnityEngineUIToggleDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "isOn",
        "onValueChanged",
        "toggleTransition",
        "graphic",
        "group",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.VFX.VisualEffect")]
    public sealed class VIServerVirtualUnityEngineVFXVisualEffectDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "visualEffectAsset",
        "initialEventName",
        "playRate",
        "startSeed",
        "resetSeedOnPlay",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.Video.VideoPlayer")]
    public sealed class VIServerVirtualUnityEngineVideoVideoPlayerDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "source",
        "url",
        "clip",
        "renderMode",
        "targetCamera",
        "targetTexture",
        "aspectRatio",
        "playOnAwake",
        "waitForFirstFrame",
        "playbackSpeed",
        "isLooping",
        "audioOutputMode",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.WheelCollider")]
    public sealed class VIServerVirtualUnityEngineWheelColliderDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "mass",
        "radius",
        "wheelDampingRate",
        "suspensionDistance",
        "forceAppPointDistance",
        "center",
        "suspensionSpring",
        "forwardFriction",
        "sidewaysFriction",
        "motorTorque",
        "brakeTorque",
        "steerAngle",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.WheelJoint2D")]
    public sealed class VIServerVirtualUnityEngineWheelJoint2DDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
    {
        "motor",
        "useMotor",
        "suspension",
    };

        public override HashSet<string> Keywords => _keywords;
    }

    [VIServerVirtualObjectNameAttribute("UnityEngine.WindZone")]
    public sealed class VIServerVirtualUnityEngineWindZoneDrawer : VIServerVirtualObjectDrawer
    {
        private static readonly HashSet<string> _keywords = new HashSet<string>
        {
            "mode",
            "radius",
            "windMain",
            "windTurbulence",
            "windPulseMagnitude",
            "windPulseFrequency",
        };

        public override HashSet<string> Keywords => _keywords;
    }
}
