using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Strix.VirtualInspector.Server.Editor
{
    public static class VIServerVirtualDrawerCodeGenerator
    {
        public static string GenerateDrawersCode(
            Dictionary<string, HashSet<string>> componentsMembers,
            string targetNamespace = "Strix.VirtualInspector.Client.Editor")
        {
            if (componentsMembers == null)
                throw new ArgumentNullException(nameof(componentsMembers));

            var sb = new StringBuilder();

            // --- Header ---
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file was generated by VIServerVirtualDrawerCodeGenerator.");
            sb.AppendLine("// DO NOT EDIT MANUALLY.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(targetNamespace))
            {
                sb.AppendLine($"namespace {targetNamespace}");
                sb.AppendLine("{");
            }

            foreach (var kv in componentsMembers.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                var fullTypeName = kv.Key?.Trim();
                if (string.IsNullOrEmpty(fullTypeName))
                    continue;

                var className = MakeDrawerClassName(fullTypeName);
                var keywords = kv.Value ?? new HashSet<string>();

                sb.AppendLine($"    [VIServerVirtualObjectNameAttribute(\"{EscapeString(fullTypeName)}\")]");
                sb.AppendLine($"    public sealed class {className} : VIServerVirtualObjectDrawer");
                sb.AppendLine("    {");

                var items = keywords
                    .Where(s => !string.IsNullOrWhiteSpace(s))
                    .Distinct(StringComparer.Ordinal)
                    .OrderBy(s => s, StringComparer.Ordinal)
                    .ToArray();

                sb.AppendLine("        private static readonly HashSet<string> _keywords = new HashSet<string>");
                sb.AppendLine("        {");
                foreach (var s in items)
                    sb.AppendLine($"            \"{EscapeString(s)}\",");
                sb.AppendLine("        };");
                sb.AppendLine();
                sb.AppendLine("        public override HashSet<string> Keywords => _keywords;");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(targetNamespace))
                sb.AppendLine("}");

            return sb.ToString();
        }

        // --- Helpers ---
        public static string MakeDrawerClassName(string fullTypeName)
        {
            var raw = "VIServerVirtual" + fullTypeName.Replace(".", "").Replace("+", "") + "Drawer";
            return SanitizeIdentifier(raw);
        }

        static string SanitizeIdentifier(string s)
        {
            if (string.IsNullOrEmpty(s))
                return "_";
            var chars = s.ToCharArray();
            for (int i = 0; i < chars.Length; i++)
            {
                char c = chars[i];
                bool ok = (c == '_' || char.IsLetterOrDigit(c));
                if (!ok)
                    chars[i] = '_';
            }
            if (!(char.IsLetter(chars[0]) || chars[0] == '_'))
                return "_" + new string(chars);
            return new string(chars);
        }

        static string EscapeString(string s) =>
            s?.Replace("\\", "\\\\").Replace("\"", "\\\"") ?? "";
    }


}
